use lightflow::preload::*;

pub fn define() -> WorkflowSpec {
    workflow!()
        .name("Video Render Edit")
        .description("Render a structured edit decision plan into a video artifact using the repository ffmpeg renderer.")
        .input("edit_plan", "json")
        .input_description("edit_plan", "Edit decision plan with output settings and ordered timeline segments.")
        .input_required("edit_plan", true)
        .input_widget("edit_plan", "json")
        .input("output_path", "path")
        .input_description("output_path", "Destination MP4 path for the rendered edit.")
        .input_required("output_path", true)
        .input_widget("output_path", "file_save")
        .input_artifact_kind("output_path", "video")
        .output("video", "artifact")
        .output_description("video", "Rendered video artifact metadata.")
        .output_artifact_kind("video", "video")
        .output("video_path", "path")
        .output_description("video_path", "Path to the rendered MP4 file.")
        .output_artifact_kind("video_path", "video")
        .output("render_summary", "text")
        .output_description("render_summary", "Human-readable render summary.")
        .build()
}
