use lightflow::preload::*;
use lightflow::runner::Response;
use lightflow::serde_json::{Map, Value};

pub const WORKFLOW_ID: &str = "lightflow.video_work_speech";
pub const WORKFLOW_VERSION: &str = env!("CARGO_PKG_VERSION");

pub fn define() -> WorkflowSpec {
    workflow! {
    name: "Video Work Speech Generation", description: "Rust-native speech generation from a consent-gated Video Work API voice profile.",
    input "speaker_id": "text" { description: "Video Work API speaker ID.", required: true, widget: "text", }
    input "profile_id": "text" { description: "Consent-gated voice profile ID.", required: true, widget: "text", }
    input "target_text": "text" { description: "Text to synthesize.", required: true, widget: "textarea", }
    input "speed": "number" { description: "Speech speed from 0.75 through 1.25.", required: false, default: 1.0, range: [0.75, 1.25, 0.05], widget: "slider", }
    output "generation": "json" { description: "Completed Video Work API generation result with audio metadata." }
    output "summary": "text" { description: "Rust-native workflow summary." }
}.builtin_runtime("command", "lightflow.command.run", "process.command.v1").build()
}

pub fn execute(inputs: &Map<String, Value>) -> Result<Response, SpeechError> {
    let mut arguments = Map::new();
    for name in ["speaker_id", "profile_id", "target_text"] {
        let value = inputs
            .get(name)
            .and_then(Value::as_str)
            .filter(|value| !value.trim().is_empty())
            .ok_or_else(|| SpeechError::new("speech text input must be non-empty"))?;
        arguments.insert(name.to_owned(), value.trim().into());
    }
    let speed = inputs.get("speed").and_then(Value::as_f64).unwrap_or(1.0);
    if !(0.75..=1.25).contains(&speed) {
        return Err(SpeechError::new(
            "speed must be a number from 0.75 through 1.25",
        ));
    }
    arguments.insert("speed".to_owned(), speed.into());
    let generation =
        lightflow_video_work_mcp::call("generate_speech", arguments).map_err(SpeechError::from)?;
    validate_generation(&generation)?;
    Ok(Response {
        outputs: Map::from_iter([
            ("generation".to_owned(), generation.into()),
            (
                "summary".to_owned(),
                "Speech generated by Rust-native Video Work API workflow.".into(),
            ),
        ]),
        artifacts: Vec::new(),
        replay_fingerprint: Map::from_iter([(
            "implementation".to_owned(),
            implementation_identity().into(),
        )]),
    })
}

fn validate_generation(generation: &Map<String, Value>) -> Result<(), SpeechError> {
    for field in ["id", "audio_url", "audio_path"] {
        generation
            .get(field)
            .and_then(Value::as_str)
            .filter(|value| !value.trim().is_empty())
            .ok_or_else(|| SpeechError::new(format!("generation {field} must be non-empty")))?;
    }
    if generation.get("status").and_then(Value::as_str) != Some("complete") {
        return Err(SpeechError::new("generation status must be complete"));
    }
    if !generation.get("audio").is_some_and(Value::is_object) {
        return Err(SpeechError::new("generation audio must be an object"));
    }
    Ok(())
}

fn implementation_identity() -> String {
    format!(
        "lightflow.video_work_speech.rust.fnv1a64:{:016x}",
        digest(include_bytes!("lib.rs"))
    )
}
const fn digest(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf2_9ce4_8422_2325;
    let mut index = 0;
    while index < bytes.len() {
        hash ^= bytes[index] as u64;
        hash = hash.wrapping_mul(0x100_0000_01b3);
        index += 1;
    }
    hash
}
#[derive(Debug)]
pub struct SpeechError(String);
impl SpeechError {
    fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }
}
impl From<lightflow_video_work_mcp::Error> for SpeechError {
    fn from(value: lightflow_video_work_mcp::Error) -> Self {
        Self(value.to_string())
    }
}
impl std::fmt::Display for SpeechError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.0)
    }
}
impl std::error::Error for SpeechError {}

#[cfg(test)]
mod tests {
    use super::*;
    use lightflow::serde_json::json;

    #[test]
    fn accepts_completed_generation_payload() {
        let payload = json!({
            "id": "generation-1",
            "status": "complete",
            "audio_url": "/api/generations/generation-1/audio",
            "audio_path": "/var/lib/video-work/generation-1.wav",
            "audio": {"duration_seconds": 1.5}
        });
        assert!(validate_generation(payload.as_object().unwrap()).is_ok());
    }

    #[test]
    fn rejects_incomplete_generation_payload() {
        for payload in [
            json!({"status": "complete", "audio_url": "/audio", "audio_path": "/audio.wav", "audio": {}}),
            json!({"id": "generation-1", "status": "running", "audio_url": "/audio", "audio_path": "/audio.wav", "audio": {}}),
            json!({"id": "generation-1", "status": "complete", "audio_url": "", "audio_path": "/audio.wav", "audio": {}}),
            json!({"id": "generation-1", "status": "complete", "audio_url": "/audio", "audio_path": "/audio.wav", "audio": []}),
        ] {
            assert!(validate_generation(payload.as_object().unwrap()).is_err());
        }
    }
}
